# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20170921_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhesusuario',
            name='ultimamodificacao',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 21, 12, 42, 34, 430363, tzinfo=utc)),
        ),
    ]
