# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_detalhesusuario_ultimamodificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhesusuario',
            name='ultimamodificacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
